/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TravelCarbonSimulatorImport } from './routes/travel-carbon-simulator'
import { Route as IndexImport } from './routes/index'
import { Route as CompanyIdImport } from './routes/company.$id'

// Create/Update Routes

const TravelCarbonSimulatorRoute = TravelCarbonSimulatorImport.update({
  path: '/travel-carbon-simulator',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CompanyIdRoute = CompanyIdImport.update({
  path: '/company/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/travel-carbon-simulator': {
      preLoaderRoute: typeof TravelCarbonSimulatorImport
      parentRoute: typeof rootRoute
    }
    '/company/$id': {
      preLoaderRoute: typeof CompanyIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  TravelCarbonSimulatorRoute,
  CompanyIdRoute,
])

/* prettier-ignore-end */
